### ISSUE TITLE
Order-independent $splice?

### ISSUE THREAD

**Issue by mnpenner** [kolodny/immutability-helper#12]
This is actually a problem I ran into with [react-addons-update](https://facebook.github.io/react/docs/update.html), but that's deprecated now, so I'm filing it here.

I would expect these two operations to give the same result:

```js
> var update = require('immutability-helper');
> update([0,1,2,3,4,5], {$splice: [[1,1],[3,1]]})
[ 0, 2, 3, 5 ]
> update([0,1,2,3,4,5], {$splice: [[3,1],[1,1]]})
[ 0, 2, 4, 5 ]
```

i.e., if I want to remove indices `1` and `3` I wouldn't expect them to "shift" in the middle of the operation.

**Comment by kolodny** [comment]
[In general when removing things from arrays you'd want to iterate in reverse.](http://stackoverflow.com/a/9882349) I'm not really comfortable peeking into the splice arrays, so I suggest either specifying higher indices operations first, or making a copy with `slice()` and mutating the array directly.

I've never really understood why `$splice` takes an array of arrays instead of just taking a single array.

**Comment by mnpenner** [comment]
Yes, I figured out that it needs to be reversed, but this is a *helper* library, I figure it could do that for us.

It takes an array of arrays because how else can modify two different sections of the same array?

For anyone that wants this feature, I created a [fork](https://github.com/nucleuslabs/immutability-helper).
