### ISSUE TITLE
$set object in a Map where key is an object

### ISSUE THREAD

**Issue by Zhephyr54** [kolodny/immutability-helper#128]
I am trying to use immutability-helper to update an object in a Map where keys are objects :
`const updatedAppsMap = update(this.state.appsMap, { appId: { $set: updatedApp} });` where `appId` is the key (as an object).

It results in a new item getting added to the Map with "appId" as the key. 
I don't know if it's just me not getting the right syntax or if it's something not supported/possible the way I am trying to do.
Thanks !

**Comment by Zaynex** [comment]
The Map just like array.
```
const MapData = new Map();
const appId = {'id': 'elfjsdb30f'};
MapData.set(appId, 'I am appId value');
```
![image](https://user-images.githubusercontent.com/13745971/49843467-508efe80-fdfa-11e8-9c0c-f9f739ddd717.png)

And in react:
![image](https://user-images.githubusercontent.com/13745971/49843489-64d2fb80-fdfa-11e8-9c2c-589ba364dc3c.png)

You can't find the key `appId object` because the key in map is index. 
@Zhephyr54
