### ISSUE TITLE
Object.prototype.toString.call (MapObj) isn't supported in IE 11

### ISSUE THREAD

**Issue by wxywj1005** [kolodny/immutability-helper#136]
Some operations working with Map/Set doesn't work in IE 11.
Just Increase the judgment of instanceof in index.ts can fix it maybe.

**Comment by WangMango** [comment]
Similar issues appeared just for IE11 and I had to refactor code using add/remove API.
Is this way the only workaround? I don't think the polyfill approach will work since this library is explicitly expecting Set/Map. However, it is risky to rely on not using add/remove, since anyone without knowing this bug may make this mistake in the future.
Any suggestions?

Error message looks like this:
SCRIPT5022: update(): $add expects a target of type Set or Map; got Object
SCRIPT5022: update(): $remove expects a target of type Set or Map; got Object

**Comment by kolodny** [comment]
Closing since IE isn't a concern for this library
