### ISSUE TITLE
How to set currently-undefined nested structure? 

### ISSUE THREAD

**Issue by jfeldstein** [kolodny/immutability-helper#16]
Not really an issue, but hoping for a best practice, perhaps. 

```
> update({}, {a: {b: {c: {$set: true}}}})
TypeError: Cannot read property 'b' of undefined
    at update (/Users/jordan/Code/kiddom/teacherdashboard/node_modules/immutability-helper/index.js:65:44)
    at update (/Users/jordan/Code/kiddom/teacherdashboard/node_modules/immutability-helper/index.js:65:31)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
```

My target doesn't have all the keys. Is there a clean way to deep-set the structure from source?

**Comment by kolodny** [comment]
Perhaps something like this?

```js
var spec = {a: {b: {c: {$set: true}}}}
console.log(
  JSON.stringify(update(spec, spec), 0, 2)
)
/* outputs:
{
  "a": {
    "b": {
      "c": true
    }
  }
}
*/
```

You can also try something like https://lodash.com/docs/4.17.4#set

**Comment by IstoraMandiri** [comment]
Thanks @kolodny, but i'm still not sure how i should go about certain situations:

```javascript
// what's the best practice for turning:
const state = {
  a: { },
  b: { c: { } },
  z: false,
};
// into:
const state = {
  a: { d: { e: { f: 'thing' } } },
  b: { c: { } },
  z: false,
};
```

In my situation `a` might or might not have nesting defined yet, and by default it doesn't. Is there a one-size-fits-all approach for updating `f` when we don't whether `a` is nested and also being agnostic to `b` and `z`? Using `update(state, { a: { d: { e: { f: { $set: 'thing' } } })` is throwing first time, but works as expected once `f` (or even `e`) is set.

**Comment by lyxell** [comment]
@hitchcott Did you find a solution for this?

**Comment by IstoraMandiri** [comment]
@lyxell Nope, had to manually ensure that the structure exists before udpating

**Comment by kolodny** [comment]
The reason I'm choosing not to implement this is because you really can't make any assumptions about what an object that isn't there is supposed to be. Consider the following:


```js
function Foo() { this.bar = true }
Foo.prototype.foos = function() { console.log('fooing ' + this.test ) }
var update = require("immutability-helper")
var o1 = {foo: new Foo, arr: []}

var o2 = update(o1, {foo: {test: {$set: 'thing'}}});
o2.foo.foos() // "fooing thing"

var o3 = update(o1, {arr: {0: {$set: 'value'}}})
o3.arr.map(v => v.toUpperCase()) // ['VALUE']
```

[This runs as expected](https://runkit.com/5815f2f3cfa862001346a618/58d8528e69bd5800151f649e) however if we were to fill the object with plain objects, when they should sometimes be arrays or some object more exotic, things will start falling apart.

This library is meant to be a helper for using objects immutability (hence the name), similarly, you can't do the following with mutable objects

```js
var obj = {}
obj.a.b.c = 'obj.a.b.c' // Uncaught TypeError: Cannot read property 'b' of undefined
```

**Comment by hoytech** [comment]
I agree, it's a pretty big pain having to maintain an empty skeleton structure in your state components. The behaviour some of you are suggesting, where it automatically creates the necessary containers to satisfy the update, is called [autovivification](https://en.wikipedia.org/wiki/Autovivification).

I have created a mostly-compatible module called [update-immutable](https://www.npmjs.com/package/update-immutable) which implements this feature. For example, the use-case that started this ticket:

<pre>
> update({}, {a: {b: {c: {$set: true}}}})
{ a: { b: { c: true } } }
</pre>

The problems that @kolodny mentioned are in my experience generally non-issues. If parts of your code assume a key holds an object and other parts assume the same key holds an array, your program is likely to misbehave entirely apart from the autovivification behaviour. The only time it gets kind of weird is if you try to auto-vivify a nested array into existence, which is not supported:

<pre>
> update({}, {a: {0: {c: {$set: true}}}})
{ a: { '0': { c: true } } }
</pre>

So don't do that. Note that autovivifying an array into existence with a push (for example) is fine since it's obvious you mean that key to be an array:

<pre>
> JSON.stringify(update({}, {a: {b: {c: {$push: [1,2,3]}}}}))
'{"a":{"b":{"c":[1,2,3]}}}'
</pre>

(I'm just JSON stringifying so node repl doesn't abbreviate the deeply nested structure)

Hope this helps.
