### ISSUE TITLE
Numeric keys don't work for Maps

### ISSUE THREAD

**Issue by infojunkie** [kolodny/immutability-helper#170]
The following test fails with `TypeError: Cannot read property 'apple' of undefined`:
```
  it('supports nested objects inside Maps with numeric keys', () => {
    const state = new Map([
      [42, { banana: 'yellow', apple: ['red'], blueberry: 'purple' }],
    ]);

    const updatedState = update(state, {
      [42]: { apple: { $set: ['green', 'red'] } },
    } as any);

    expect(updatedState).toEqual(
      new Map([
        [
          42,
          { banana: 'yellow', apple: ['green', 'red'], blueberry: 'purple' },
        ],
      ]),
    );
  });
```

**Comment by kolodny** [comment]
This library doesn't "delve" into Maps and Sets. I'm happy to accept a PR that includes this functionality

**Comment by Ethorsen** [comment]
Yes please!!  Just found out, if you try to set a Map element with an int key, it will just insert another element with its string equivalent as a key and you'll end up with 2 elements.

```
const state = new Map([[42, "hey ho"]]);
const updatedState = update(state, {
      [42]: { $set: "ho hey" }
});
```

updatedState now looks like
```
Map([
   [ 42, "hey ho" ],
   [ "42", "ho hey" ],
])
```

For now and because I update the whole element, I'm working around by re-adding the element if it exists.  It will effectively overwrite the previous element for that key.
```
if (state.myMap.has(myId)) {
  return update(state, {
    myMap: { $add: [[myId, myNewElement]] },
  });
}
```
