### ISSUE TITLE
Use the doc from React repo

### ISSUE THREAD

**Issue by gaearon** [kolodny/immutability-helper#2]
I think it would be great if the doc was moved here because we plan to eventually remove it.
The new functionality could be described together with the old one.

**Comment by kolodny** [comment]
I started with this https://github.com/kolodny/immutability-helper/tree/react-immutability-helpers-readme

Writing docs isn't my strong point so I may need some help with this. Also since this repo isn't react specific it makes merging in the react docs feel a little forced.

I'm ok with this repo being more react-centric and just using the react docs assuming people are coming here because of the react and redux docs.

Let me know what you think

**Comment by hongyuan1306** [comment]
I think it's time to merge the react docs into the master branch.

I for one was referred to this project from the react site. But once I start to use this library, it is quite natural for me to check the docs for syntax on the GitHub project homepage. Having to go back to the react site is really cumbersome.

**Comment by kolodny** [comment]
Published in `2.1.0`
