### ISSUE TITLE
TypeScript error on update method:  TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/immutability-helper/index"' has no compatible call signatures.

### ISSUE THREAD

**Issue by ajalgaonkar** [kolodny/immutability-helper#96]
I am currently getting the following issue:
 TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "~/node_modules/immutability-helper/index"' has no compatible call signatures.

This issue does not happen on the 2.6.4 version but as soon as the solution pulled in the 2.6.5 version i started getting this issue.
For now I have made the version constant at 2.6.4, but wanted to notify you about this issue.

Thanks.

**Comment by andreiglingeanu** [comment]
Thanks. Could you please post a code snippet so that we can reproduce the problem?

**Comment by chitswe** [comment]
@ajalgaonkar  You need to change import statement. Use `import update from "immutability-helper";` instead of `import * as update from "immutability-helper"`. Because typescript type declaration file has been changed in 2.6.5.

**Comment by andreiglingeanu** [comment]
I believe yes, we did this change. I think it's better to just have a default export & everyone should be using `import update from "immutability-helper";`

**Comment by DavidHall** [comment]
I have hit the same problem with the typescript definition change in 2.6.5, and although changing my import from `import * as update from "immutability-helper"` to `import update from "immutability-helper"` does resolve the compiler error, I now hit run time errors.

The run time error I see is:

    TypeError: immutability_helper_1.default is not a function

And that is just from a standard call like:

    const newData = update(myData, {
        x: {y: {z: {$set: 7}}},
        a: {b: {$push: [9]}}
    });

It could be that the problem is somewhere in my webpack setup, with that not correctly identifying the default export as a function.

One work around that I found is to call the `newContext()` function to create a new function that does work:

```
import { newContext } from "immutability-helper";
const update = newContext();
```

**Comment by chitswe** [comment]
@DavidHall I also have the same problem like you with new version. I thought it could be the problem with webpack configuration. So I didn't report it here.

**Comment by andreiglingeanu** [comment]
Oh, this sounds bad, I guess it's because we have declared the `update` function as a default ES6 export in typings & in the actual source code we have a common JS export `module.exports = newContext()`.

I guess we'll need the typings to fix the library code to get it working, at least because the README says that an ES6 default import is a valid way of consuming the lib: `import update from 'immutability-helper';`

**Comment by vvolodin** [comment]
any workaround for this? having runtime errors too. importing {newContext} does not compile for me.

update: my solution to this was using the older `* as` syntax and casting it to any after importing...

**Comment by atfzl** [comment]
@andreiglingeanu instead of:
```js
module.exports = newContext();
module.exports.newContext = newContext;
```

we should change it to:
```js
module.exports = newContext();
module.exports.default = newContext();
module.exports.newContext = newContext;
```

It is working after adding default export here.

**Comment by andreiglingeanu** [comment]
It seems like that is the way to go, a bit hacky though...

I opened a PR for that, please try it

**Comment by ob-ivan** [comment]
For those who are like me:

```
find src -name '*.tsx' | xargs sed -i 's/import \* as update from "immutability-helper";/import update from "immutability-helper";/'
```

**Comment by bhagyas** [comment]
Issue continues to exist on 2.7.0. Downgrading the dependency version to 2.6.4 seems to work.
